CREATE TABLE segmentos(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NULL
);

CREATE TABLE interesses(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT UNSIGNED NULL,
    segmento_id INT UNSIGNED NULL,
    FOREIGN KEY(segmento_id) REFERENCES segmentos(id)
);

CREATE TABLE contratos(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    caminho_s3 VARCHAR(255) NULL,
    assinatura VARCHAR(255) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE acoes_voluntariado(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome_acao VARCHAR(255) NULL,
    nivel VARCHAR(255) NULL,
    fase VARCHAR(255) NULL,
    formato VARCHAR(255) NULL,
    data_inicio DATE NULL,
    data_termino DATE NULL,
    tipo VARCHAR(255) NULL,
    horario TIMESTAMP NULL,
    local VARCHAR(255) NULL,
    informacoes_adicionais TEXT NULL,
    imagem VARCHAR(255) NULL,
    vagas INT NULL,
    url VARCHAR(255) NULL,
    meta DECIMAL(10, 2) NULL,
    tipo_meta VARCHAR(255) NULL,
    campanha TINYINT(1) NULL,
    publica TINYINT(1) NULL,
    valor_personalizado TINYINT(1),
    contrato_id INT UNSIGNED NULL,
    segmento_id INT UNSIGNED NULL,
    usuario_id INT UNSIGNED NULL,
    organizacao_id INT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(contrato_id) REFERENCES contratos(id),
    FOREIGN KEY(segmento_id) REFERENCES segmentos(id)
);

CREATE TABLE arquivos(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    caminho_s3 VARCHAR(255) NULL,
    nome_arquivo_original VARCHAR(255) NULL,
    tamanho LONG NULL,
    acao_id INT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(acao_id) REFERENCES acoes_voluntariado(id)
);

CREATE TABLE inscricoes(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    assinatura_digital VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    usuario_id INT UNSIGNED NULL,
    acao_id INT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(acao_id) REFERENCES acoes_voluntariado(id)
);

CREATE TABLE opcoes_contribuicao(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    valor DECIMAL(10, 2) NULL,
    descricao VARCHAR(255) NULL,
    acao_id INT UNSIGNED NULL,
    FOREIGN KEY(acao_id) REFERENCES acoes_voluntariado(id)
);

CREATE TABLE doadores(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NULL,
    cpf VARCHAR(255) UNIQUE NULL,
    email VARCHAR(255) NULL,
    telefone VARCHAR(255) NULL,
    data_nascimento DATE NULL,
    usuario_id INT UNSIGNED NULL
);

CREATE TABLE doacoes(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(255) NULL,
    metodo VARCHAR(255) NULL,
    link VARCHAR(255) NULL,
    valor VARCHAR(255) NULL,
    status VARCHAR(255) NULL,
    acao_id INT UNSIGNED NULL,
    doador_id INT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(acao_id) REFERENCES acoes_voluntariado(id),
    FOREIGN KEY(doador_id) REFERENCES doadores(id)
);
